### ISSUE TITLE
Bug? Any(match) fails if it finds more than 1 match

### ISSUE THREAD

**Issue by roycornelissen** [riezebosch/hypothesist#2]
I have a hypothesis that uses `.Any( match )`, and it fails with:

```
Hypothesist.InvalidException : I expected at least 1 matches but found only 8.
```
But I think 8 also qualifies for `Any` :) Am I doing something wrong?

**Comment by roycornelissen** [comment]
Hm, it happens when I chain assertions:

```csharp
Hypothesis.For<Message>()
   .Exactly(2, m => m.Name == "Manuel")
   .Any(m => m.Type == "ACK");
```
This yields the exception above, but when I split it in two separate ones, they both succeed.

```csharp
Hypothesis.For<Message>()
   .Exactly(2, m => m.Name == "Manuel");
Hypothesis.For<Message>()
   .Any(m => m.Type == "ACK");
```

**Comment by riezebosch** [comment]
That's a bug 🥳

**Comment by riezebosch** [comment]
Fix: https://github.com/riezebosch/hypothesist/commit/19536a5632d6fe43d3dd02d93e7a40ad9bb54b4f
